CREATE TABLE `cmc_exchanges` (
	`timestamp`	INTEGER NOT NULL UNIQUE,
	`Trade Satoshi_GRLC/BTC`	REAL NOT NULL,
    `CoinFalcon_GRLC/BTC`	REAL NOT NULL,
    `CryptoBridge_GRLC/BTC`	REAL NOT NULL,
    `Nanex_GRLC/NANO`	REAL NOT NULL,
    `Trade Satoshi_GRLC/LTC`	REAL NOT NULL,
    `Trade Satoshi_GRLC/BCH`	REAL NOT NULL,
    `Trade Satoshi_GRLC/DOGE`	REAL NOT NULL,
    `Trade Satoshi_GRLC/USDT`	REAL NOT NULL,
    `CoinFalcon_GRLC/ETH`	REAL NOT NULL,
	PRIMARY KEY(`timestamp`)
);

CREATE TABLE "cmc_usd_1d" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cmc_usd_1w" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cmc_usd_1m" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cmc_usd_3m" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cmc_btc_1d" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cmc_btc_1w" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cmc_btc_1m" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cmc_btc_3m" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "nanex_1d" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "nanex_1w" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "nanex_1m" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "nanex_3m" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cb_1d" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cb_1w" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cb_1m" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "cb_3m" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "ts_1d" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "ts_1w" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "ts_1m" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );

CREATE TABLE "ts_3m" (
	`id` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`timestamp` INTEGER NOT NULL,
	`open` REAL NOT NULL,
	`close` REAL NOT NULL,
	`high` REAL NOT NULL,
	`low` REAL NOT NULL );
